name: Flutter Build
on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: List file is repo
        run: |
          ls -a
      - name: Setup xcode version    
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.0'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.10'
          channel: 'stable'
          cache: true
      - run: flutter --version
      - name: Get Flutter dependencies
        run: |
          flutter clean
          flutter pub get
      - name: Setup | Rust 
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy   
      - name: Checkout rust version
        run: rustc --version   
      - name: install frb codegen
        run: cargo install flutter_rust_bridge_codegen@1.56.0
      - name: install cargo lipo
        run: cargo install cargo-lipo
      - name: install llvm
        run: brew install llvm    
      - name: running codegen
        run: |
          make ios
          cd ios/Runner
          ls -a
      - name: build ios
        run: flutter build ios --no-codesign    