name: Flutter Build
on:
  push:
    branches: ["main"]
env:
  flutter_version: "3.3.10"
  cargo_lipo: "cargo_lipo_v1"
  frb_gen: "frb_gen_v1"


jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Setup xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "14.0"
      - uses: actions/cache@v3
        id: cache-deps
        with:
          path: |
            /Users/runner/hostedtoolcache/flutter
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            ./src_rust/target/
          key: ${{ runner.OS }}-cargo-install-cache-v1}}
      - uses: actions/cache@v3
        id: cache-lipo
        with:
          path: |
            ~/.cargo/bin/cargo-lipo
          key: ${{ runner.OS }}-cargo-lipo-cache-${{env.cargo_lipo}}
      - uses: actions/cache@v3
        id: frb-gen
        with:
          path: |
            ~/.cargo/bin/flutter_rust_bridge_codegen
          key: ${{ runner.OS }}-frb-gen-cache-${{env.frb_gen}}
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.3.10"
          channel: "stable"
      - uses: actions/checkout@v3
      - name: List file is repo
        run: |
          ls -a    
      - name: Clean & Get Flutter dependencies
        run: |
          flutter clean
          flutter pub get
      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - name: rustup target
        run: |
          rustup show
          rustup target add aarch64-apple-ios
          rustup target add x86_64-apple-ios
      - name: install cargo lipo
        if: steps.cache-lipo.outputs.cache-hit != 'true'
        run: cargo install cargo-lipo
      - name: install frb codegen
        if: steps.frb-gen.outputs.cache-hit != 'true'
        run: cargo install flutter_rust_bridge_codegen@1.56.0
      - name: install llvm
        run: brew install llvm  
      - name: running codegen
        run: make ios    
      - name: build ios
        run: flutter build ios --no-codesign        

# jobs:
#   build:
#     runs-on: macos-latest
#     steps:
#       - uses: actions/cache@v3
#         with:
#           path: |
#             /Users/runner/hostedtoolcache/flutter
#           key: ${{ runner.OS }}-flutter-install-cache-${{ env.flutter_version }}
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: ${{ env.flutter_version }}
#           channel: "stable"

# jobs:
#   build:
#     runs-on: macos-latest
#     steps:
#       - uses: actions/checkout@v3
#       - name: List file is repo
#         run: |
#           ls -a
#       - name: Setup xcode version
#         uses: maxim-lobanov/setup-xcode@v1
#         with:
#           xcode-version: '14.0'
#       - uses: actions/cache@v3
#         with:
#           path: |
#             /Users/runner/hostedtoolcache/flutter
#             ~/.cargo/bin/
#             ~/.cargo/registry/index/
#             ~/.cargo/registry/cache/
#             ~/.cargo/git/db/
#             ./src_rust/target/
#           key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: '3.3.10'
#           channel: 'stable'
#       - run: flutter --version
#       - name: Get Flutter dependencies
#         run: |
#           flutter clean
#           flutter pub get
#       - name: Setup | Rust
#         uses: ATiltedTree/setup-rust@v1
#         with:
#           rust-version: stable
#           components: clippy
#       - name: Checkout rust version
#         run: rustc --version
#       - name: install frb codegen
#         run: cargo install flutter_rust_bridge_codegen@1.56.0
#       - name: install cargo lipo
#         run: cargo install cargo-lipo
#       - name: install llvm
#         run: brew install llvm
#       - name: rustup target
#         run: |
#           rustup target add aarch64-apple-ios
#           rustup target add x86_64-apple-ios
#       - name: running codegen
#         run: |
#           make ios
#           cd ios/Runner
#           ls -a
#       - name: build ios
#         run: flutter build ios --no-codesign
